const Map<String, String> appLocalizationsEn = {
  'welcome': 'Welcome to Habesha Health',
  'journey': 'Your journey to better health starts now.',
  'get_started': 'Get Started',
  'create_profile': 'Create Your Profile',
  'full_name': 'Full Name',
  'birthdate': 'mm/dd/yyyy',
  'weight': 'Weight (kg)',
  'height': 'Height (cm)',
  'fitness_label': 'Fitness Level',
  'register': 'Register',
  'welcome_back': 'Welcome back, %s!',
  'today': 'Today is %s',
  'steps': 'Steps',
  'water_intake': 'Water Intake',
  'calories_burned': 'Calories Burned',
  'log_activity': 'Log Activity',
  'weekly_report': 'Weekly Report',
  'todays_progress': 'Today\'s Progress',
  'add_water': 'Add Water',
  'meals': 'Meals',
  'exercise': 'Exercise',
  'profile': 'Profile',
  'home': 'Home',
  'settings': 'Settings',
  'todays_nutrition': 'Today\'s Nutrition: %d of %d kcal',
  'add_to_plan': 'Add to Plan',
  'start_workout': 'Start Workout',
  'fitness_level': 'Fitness Level: %s',
  'bmi': 'BMI: %s (Normal)',
  'edit_profile': 'Edit Profile',
  'save_changes': 'Save Changes',
  'theme': 'Theme',
  'light': 'Light',
  'dark': 'Dark',
  'language': 'Language',
  'english': 'English',
  'amharic': 'Amharic',
  'upload_photo': 'Upload Profile Photo',
  'please_enter_name': 'Please enter your name',
  'please_select_birthdate': 'Please select your birthdate',
  'please_enter_weight': 'Please enter your weight',
  'please_enter_valid_weight': 'Please enter a valid weight',
  'please_enter_height': 'Please enter your height',
  'please_enter_valid_height': 'Please enter a valid height',
  'please_select_fitness_level': 'Please select a fitness level',
  'choose_photo': 'Choose Photo',
  'gender': 'Gender',
  'please_select_gender': 'Please select your gender',
  'age': 'Age: %d years', // Added
  'calorie_goal': 'Calorie Goal: %d kcal/day', // Added
  'water_goal': 'Water Goal: %.1f liters/day', // Added
  'recommended_exercises': 'Recommended Exercises: %s', // Added
  'calories_gained': 'Calories Gained',
  'weekly_progress': 'Weekly Progress',
  'todays_activity': 'Today\'s Activity',
  'no_meals_today': 'No meals planned for today',
  'last_update': 'Last update: %s',
  'just_now': 'Just now',
  'minutes_ago': '%d minutes ago',
  'hours_ago': '%d hours ago',
  'no_updates_yet': 'No updates yet',
  'steps_label': '%d of %d steps',
  'water_label': '%d of %d cups',
  'calories_label': '%d of %d calories',
  'daily_goal': '%d%% of daily goal',
  'view_more': 'View More',
  'show_less': 'Show Less',
};
