const Map<String, String> appLocalizationsAm = {
  'welcome': 'እንኳን ወደ ሀበሻ ጤና ተቀበል',
  'journey': 'ወደ ተሻለ ጤና የሚወስደው ጉዞህ አሁን ይጀምራል።',
  'get_started': 'ጀምር',
  'create_profile': 'መገለጫህን ፍጠር',
  'full_name': 'ሙሉ ስም',
  'birthdate': 'ወር/ቀን/አመት',
  'weight': 'ክብደት (ኪ.ግ)',
  'height': 'ቁመት (ሴ.ሜ)',
  'fitness_label': 'የአካል ብቃት መለያ (ለምሳሌ፣ ጀማሪ፣ አትሌት)',
  'register': 'መዝግብ',
  'welcome_back': 'እንኳን ተመለስክ፣ %s!',
  'today': 'ዛሬ %s ነው',
  'steps': 'ደረጃዎች',
  'water_intake': 'የውሃ መጠን',
  'calories_burned': 'የተቃጠሉ ካሎሪዎች',
  'log_activity': 'እንቅስቃሴ መዝግብ',
  'weekly_report': 'ሳምንታዊ ሪፖርት',
  'todays_progress': 'የዛሬ እድገት',
  'add_water': 'ውሃ ጨምር',
  'meals': 'ምግቦች',
  'exercise': 'እንቅስቃሴ',
  'profile': 'መገለጫ',
  'home': 'መነሻ',
  'settings': 'ቅንብሮች',
  'todays_nutrition': 'የዛሬ ምግብ፡ %d ከ %d ካሎሪ',
  'add_to_plan': 'ወደ ዕቅድ ጨምር',
  'todays_activity': 'የዛሬ እንቅስቃሴ',
  'start_workout': 'እንቅስቃሴ ጀምር',
  'fitness_level': 'የአካል ብቃት ደረጃ፡ %s',
  'bmi': 'ቢኤምአይ፡ %s (መደበኛ)',
  'edit_profile': 'መገለጫ አርትዕ',
  'save_changes': 'ለውጦችን አስቀምጥ',
  'theme': 'ገፅታ',
  'light': 'ብርሃን',
  'dark': 'ጨለማ',
  'language': 'ቋንቋ',
  'english': 'እንግሊዝኛ',
  'amharic': 'አማርኛ',
  'upload_photo': 'የመገለጫ ፎቶ ጫን',
  'please_enter_name': 'እባክህ ስምህን አስገባ',
  'please_select_birthdate': 'እባክህ የተወለድክበትን ቀን ምረጥ',
  'please_enter_weight': 'እባክህ ክብደትህን አስገባ',
  'please_enter_valid_weight': 'እባክህ ተገቢ ክብደት አስገባ',
  'please_enter_height': 'እባክህ ቁመትህን አስገባ',
  'please_enter_valid_height': 'እባክህ ተገቢ ቁመት አስገባ',
  'please_select_fitness_level': 'እባክህ የአካል ብቃት ደረጃ ምረጥ',
  'choose_photo': 'ፎቶ ምረጥ',
  'gender': 'ፆታ',
  'please_select_gender': 'እባክህ ፆታህን ምረጥ',
  'age': 'ዕድሜ፡ %d አመት',
  'calorie_goal': 'የካሎሪ ግብ፡ %d ካሎሪ/ቀን',
  'water_goal': 'የውሃ ግብ፡ %.1f ሊትር/ቀን',
  'recommended_exercises': 'የተመከሩ እንቅስቃሴዎች፡ %s',
  'calories_gained': 'የተገኘ ካሎሪ',
  'weekly_progress': 'ሳምንታዊ እድገት',
  'no_meals_today': 'ለዛሬ የታቀዱ ምግቦች የሉም',
  'last_update': 'የመጨረሻ ዝመና፡ %s',
  'just_now': 'አሁን',
  'minutes_ago': 'ከ%d ደቂቃ በፊት',
  'hours_ago': 'ከ%d ሰዓት በፊት',
  'no_updates_yet': 'እስካሁን ዝመናዎች የሉም',
  'steps_label': '%d ከ%d ደረጃ',
  'water_label': '%d ከ%d ኩባያ',
  'calories_label': '%d ከ%d ካሎሪ',
  'daily_goal': '%d%% የዕለቱ ግብ',
  'view_more': 'ተጨማሪ አሳይ',
  'show_less': 'በትንሹ አሳይ',
};
