name: habesha_health
description: "A Flutter app for tracking health and fitness with Ethiopian context."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  pedometer: ^4.0.1
  cupertino_icons: ^1.0.8
  timezone: ^0.9.2
  image_picker: ^1.1.2
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/meals.json
    - assets/data/exercises.json
    - assets/images/logo.png
    - assets/images/icon1.png
    - assets/images/atakilt_wot.jpg
    - assets/images/chechebsa.jpg
    - assets/images/injera_firfir.jpg
    - assets/images/dulet.jpg
    - assets/images/beyaynet.jpg
    - assets/images/ful.jpg
    - assets/images/genfo.jpg
    - assets/images/kitfo.jpg
    - assets/images/tibs.jpg
    - assets/images/doro_wat.jpg
    - assets/images/shiro.png
    - assets/lang/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#F1AEAEFF"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  remove_alpha_ios: true
